### ISSUE TITLE
missing package on debian stretch

### ISSUE THREAD

**Issue by stefangweichinger** [debops/ansible-librenms#11]
Debian stretch doesn't provide php-net-ipv4 anymore, this breaks debops.librenms:

"No package matching 'php-net-ipv4' is available"

https://github.com/librenms/librenms/issues/6818

**Comment by drybjed** [comment]
This is already fixed in the DebOps monorepo, via https://github.com/debops/debops/commit/8d94c967f2c9b4d83ea61c9987da1602a53bba0a

**Comment by stefangweichinger** [comment]
sorry for the noise, I thought I use the monorepo already
